import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import clsx from "clsx";
import { Footer, Header } from "~/components/components";

const manropeVariable = localFont({
  src: "./fonts/Manrope-VariableFont_wght.ttf",
  variable: "--font-manrope-variable",
  weight: "100 700",
});

const manropeRegular = localFont({
  src: "./fonts/Manrope-Regular.ttf",
  variable: "--font-manrope-regular",
  weight: "400",
});

const manropeBold = localFont({
  src: "./fonts/Manrope-Bold.ttf",
  variable: "--font-manrope-bold",
  weight: "700",
});

// TODO Adjust Metadata

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={clsx(
          "bg-grey-light antialiased",
          manropeVariable.variable,
          manropeRegular.variable,
          manropeBold.variable
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
