name: Deploy Front to Server

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04

    env:
      SERVICE_NAME: frontend
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show current directory
        run: pwd

      - name: Show directory lists
        run: ls -la /home/runner/work/frontend/frontend

      - name: Find path of docker-compose.yml
        run: |
          find . -name "docker-compose.yml"


      # - name: Create .env file
      #   run: |
      #     echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" >> .env
      #     echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Remote Server with Rolling Update
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
            pwd ls -la
            docker-compose -f docker-compose.yml up -d --no-deps --scale ${{ env.SERVICE_NAME }}=1 --remove-orphans
            docker image prune -f
#            docker pull ghcr.io/${{ github.repository }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
#            docker-compose -f /home/runner/work/frontend/frontend/docker-compose.yml up -d --no-deps --scale ${{ env.SERVICE_NAME }}=1 --remove-orphans
#            docker image prune -f
#            docker pull ghcr.io/${{ github.repository }}/${{ env.SERVICE_NAME }}:latest
#            docker-compose up -d --no-deps --scale ${{ env.SERVICE_NAME }}=1 --remove-orphans
#            docker image prune -f

      - name: Cleanup Docker images on GitHub runner
        run: |
          docker rmi ghcr.io/${{ github.repository }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
